---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  namespace: awx
  name: awx
spec:
  service_type: NodePort
  nodeport_port: 30081
  postgres_storage_class: local-storage
  postgres_storage_requirements:
    requests:
      storage: 8Gi
  postgres_configuration_secret: awx-postgres-configuration
