---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  namespace: awx
  name: awx
spec:
  service_type: NodePort
  nodeport_port: 30081
  postgres_configuration_secret: awx-postgres-configuration
