---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
type: Opaque
stringData:
  host: awx-postgres-15.awx.svc.cluster.local
  port: "5432"
  database: awx
  username: awx
  password: awxpassword
  sslmode: prefer
  type: managed