---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
type: Opaque
stringData:
  host: host.docker.internal
  port: "5432"
  database: awx
  username: postgres
  password: postgres
  sslmode: disable
  type: unmanaged