---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: awx-postgres
  namespace: awx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: awx-postgres
  template:
    metadata:
      labels:
        app: awx-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        env:
        - name: POSTGRES_DB
          value: awx
        - name: POSTGRES_USER
          value: awx
        - name: POSTGRES_PASSWORD
          value: awxpassword
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: awx-postgres-service
  namespace: awx
spec:
  selector:
    app: awx-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP