---
apiVersion: v1
kind: Secret
metadata:
  name: awx-postgres-configuration
  namespace: awx
type: Opaque
stringData:
  host: host.k3s.internal
  port: "5432"
  database: awx
  username: awx
  password: awx-postgres-pass
  type: unmanaged
  sslmode: disable